//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.2.93
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("Home")]
	public partial class Home : PublishedContentModel, INavigationComponent, ITitleComponent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("aboutDescription")]
		public string AboutDescription
		{
			get { return this.GetPropertyValue<string>("aboutDescription"); }
		}

		///<summary>
		/// About link
		///</summary>
		[ImplementPropertyType("aboutLink")]
		public object AboutLink
		{
			get { return this.GetPropertyValue("aboutLink"); }
		}

		///<summary>
		/// Read more
		///</summary>
		[ImplementPropertyType("aboutReadMore")]
		public string AboutReadMore
		{
			get { return this.GetPropertyValue<string>("aboutReadMore"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("aboutTitle")]
		public string AboutTitle
		{
			get { return this.GetPropertyValue<string>("aboutTitle"); }
		}

		///<summary>
		/// Read more
		///</summary>
		[ImplementPropertyType("announcesReadMore")]
		public string AnnouncesReadMore
		{
			get { return this.GetPropertyValue<string>("announcesReadMore"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("announcesTitle")]
		public string AnnouncesTitle
		{
			get { return this.GetPropertyValue<string>("announcesTitle"); }
		}

		///<summary>
		/// Read more
		///</summary>
		[ImplementPropertyType("galleryReadMore")]
		public string GalleryReadMore
		{
			get { return this.GetPropertyValue<string>("galleryReadMore"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("galleryTitle")]
		public string GalleryTitle
		{
			get { return this.GetPropertyValue<string>("galleryTitle"); }
		}

		///<summary>
		/// Read more
		///</summary>
		[ImplementPropertyType("newsReadMore")]
		public string NewsReadMore
		{
			get { return this.GetPropertyValue<string>("newsReadMore"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("newsTitle")]
		public string NewsTitle
		{
			get { return this.GetPropertyValue<string>("newsTitle"); }
		}

		///<summary>
		/// #PropertyHideInNavigation: #PropertyHideInNavigationDesc
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return NavigationComponent.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// #PropertyTitle: #PropertyTitleDesc
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return TitleComponent.GetTitle(this); }
		}
	}
}
