//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.0.90
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Site</summary>
	[PublishedContentModel("Site")]
	public partial class Site : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Site";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Site(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Site, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// Facebook link
		///</summary>
		[ImplementPropertyType("facebookLink")]
		public string FacebookLink
		{
			get { return this.GetPropertyValue<string>("facebookLink"); }
		}

		///<summary>
		/// Join organization link
		///</summary>
		[ImplementPropertyType("joinOrganizationLink")]
		public object JoinOrganizationLink
		{
			get { return this.GetPropertyValue("joinOrganizationLink"); }
		}

		///<summary>
		/// Site description
		///</summary>
		[ImplementPropertyType("siteDescription")]
		public string SiteDescription
		{
			get { return this.GetPropertyValue<string>("siteDescription"); }
		}

		///<summary>
		/// Site name
		///</summary>
		[ImplementPropertyType("siteName")]
		public string SiteName
		{
			get { return this.GetPropertyValue<string>("siteName"); }
		}

		///<summary>
		/// Spadshchyna description
		///</summary>
		[ImplementPropertyType("spadshchynaDescription")]
		public string SpadshchynaDescription
		{
			get { return this.GetPropertyValue<string>("spadshchynaDescription"); }
		}

		///<summary>
		/// Internal redirect: Choose a page to redirect to when the user navigates to this page. The url won't change.
		///</summary>
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public object UmbracoInternalRedirectId
		{
			get { return this.GetPropertyValue("umbracoInternalRedirectId"); }
		}

		///<summary>
		/// Vk link
		///</summary>
		[ImplementPropertyType("vkLink")]
		public string VkLink
		{
			get { return this.GetPropertyValue<string>("vkLink"); }
		}
	}
}
