//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1225 with alias "subtitleComponent"
	/// <summary>Subtitle</summary>
	public partial interface ISubtitleComponent : IPublishedContent
	{
		/// <summary>#PropertySubtitle</summary>
		string Subtitle { get; }
	}

	/// <summary>Subtitle</summary>
	[PublishedContentModel("subtitleComponent")]
	public partial class SubtitleComponent : PublishedContentModel, ISubtitleComponent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "subtitleComponent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SubtitleComponent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SubtitleComponent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// #PropertySubtitle: #PropertySubtitleDesc
		///</summary>
		[ImplementPropertyType("subtitle")]
		public string Subtitle
		{
			get { return GetSubtitle(this); }
		}

		/// <summary>Static getter for #PropertySubtitle</summary>
		public static string GetSubtitle(ISubtitleComponent that) { return that.GetPropertyValue<string>("subtitle"); }
	}
}
